### ISSUE TITLE
Filesystem options not working in 1.8b541

### ISSUE THREAD

**Issue by UbiquitousChris** [MagerValp/AutoDMG#190]
Greetings,

When trying to build an image with the CLI version of AutoDMG, specifying the Filesystem option, either as a command option or as part of a template, results in AutoDMG crashing with the following error:

```
2017-09-18 13:31:01.662 AutoDMG[4576:47506] AutoDMG died with an uncaught exception 'IEDTemplate' object has no attribute 'get': Traceback (most recent call last):
  File "/Volumes/AutoDMG-1.8b541/AutoDMG.app/Contents/Resources/main.py", line 217, in main
    status = cli_main(decoded_argv)
  File "/Volumes/AutoDMG-1.8b541/AutoDMG.app/Contents/Resources/main.py", line 171, in cli_main
    return args.func(args)
  File "/Volumes/AutoDMG-1.8b541/AutoDMG.app/Contents/Resources/IEDCLIController.py", line 228, in cmdBuild_
    self.workflow.setFilesystem_(template.get("Filesystem"))
AttributeError: 'IEDTemplate' object has no attribute 'get'
```

Our template file looks like the following:

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AdditionalPackages</key>
	<array>
		<string>/Volumes/Packages/LMCO/CreateSystemConfig/LMCO-CreateSystemConfig-1.0.pkg</string>
	</array>
	<key>Filesystem</key>
	<string>hfs</string>
	<key>OutputPath</key>
	<string>/tmp/AVE-BaseImage-10.13-20170918.hfs.dmg</string>
	<key>SourcePath</key>
	<string>/Applications/Install macOS High Sierra Beta.app</string>
	<key>TemplateFormat</key>
	<string>1.0</string>
	<key>VolumeName</key>
	<string>Macintosh HD</string>
</dict>
</plist>`

**Comment by MagerValp** [comment]
Sorry about that, that's what I get for releasing before I've finished testing... I released a new beta, try [AutoDMG v1.8b544](https://github.com/MagerValp/AutoDMG/releases/tag/v1.8b544).

**Comment by UbiquitousChris** [comment]
Woohoo! Its working again. Thanks for your quick action :)
